[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
csv = "1.2.1"
chrono = { version = "0.4.24", features = ["serde"] }
regex = "1" 
lazy_static = "1.4"